// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVzwe0awg11KXtSDNf_tcKLtxL-1i-3mU',
    appId: '1:285740123841:web:ed7fc20e5a78f760feb640',
    messagingSenderId: '285740123841',
    projectId: 'chao-60cf5',
    authDomain: 'chao-60cf5.firebaseapp.com',
    storageBucket: 'chao-60cf5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQg2kE9cRjyESGco804o2jbRUEhY6Sqos',
    appId: '1:285740123841:android:81f9d8a8e4b0b4f6feb640',
    messagingSenderId: '285740123841',
    projectId: 'chao-60cf5',
    storageBucket: 'chao-60cf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1BsfXOiZCLqcpY2BP_luHShbixFEJIkg',
    appId: '1:285740123841:ios:0f7d3b12cecbebcbfeb640',
    messagingSenderId: '285740123841',
    projectId: 'chao-60cf5',
    storageBucket: 'chao-60cf5.appspot.com',
    iosClientId: '285740123841-7n3qjjtf6h05kadguq252vf2jbq7till.apps.googleusercontent.com',
    iosBundleId: 'com.chao.app',
  );
}
